### ISSUE TITLE
00. INTERIM STATE

### ISSUE THREAD

**Issue by erikacrd** [Capital-Regional-District/EDRMS#123]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
This epic contains the work related to the EDRMS interim state for divisions such as Regional Parks, etc that are requesting to get help with their SharePoint sites

#Outcome:
- [ ]  Communications to the affected areas
- [ ] Analysis and plans of what can vs what cannot be done ahead of the full EDRMS work
- [ ] Training plans and delivery where relevant
